# Wingtheme dark

[colors.primary]
background = '#09090b'
foreground = '#fafafa'

[colors.cursor]
cursor = '#3d88c5'
text = '#09090b'

[colors.selection]
background = '#1f5f91'
text = '#fafafa'

[colors.normal]
black   = '#09090b'
red     = '#ff6467'
green   = '#45d175'
yellow  = '#e8bd67'
blue    = '#3d88c5'
magenta = '#b89bdb'
cyan    = '#67c9d8'
white   = '#9f9fa9'

[colors.bright]
black   = '#71717a'
red     = '#ff8789'
green   = '#73e39a'
yellow  = '#f4cf7d'
blue    = '#74b6e7'
magenta = '#cfb6eb'
cyan    = '#8ee0eb'
white   = '#fafafa'
